name: attendance
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.0-146.2.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.0.0
  page_transition: ^2.1.0
  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  shamsi_date: ^1.0.2 
  dio: ^5.4.0
  device_info_plus: ^9.1.2
  flutter_svg: ^2.0.10+1
  network_info_plus: ^4.1.0+1
  connectivity_plus: ^5.0.2
  lottie: ^3.1.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  encrypt: ^5.0.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/image/
    - assets/server_data/
    - assets/map/
    - assets/svg/
    - assets/lottie/
 
